repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        args: ['--max-line-length', '110', '--in-place']
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: ['--max-line-length', '110']
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      -   id: prettier
          files: '^frontend/.*\.(ts|tsx)'
          args: ['--parser', 'typescript', '--write']